import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Toast from "./provider/toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Usebook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toast />
        {children}
        </body>
    </html>
  );
}
